### ISSUE TITLE
SSL deployment

### ISSUE THREAD

**Issue by kofalt** [gitterHQ/irc-bridge#10]
As it's possible to use gitter for private rooms, it'd be nice not to cleartext :)

**Comment by malditogeek** [comment]
Totally. This was in beta, that's why there was no SSL support.

I've *just* deployed it to production, so you can connect now to the bridge at `irc.gitter.im` using SSL.

Will add some instructions in the README :+1:

**Comment by kofalt** [comment]
Most excellent :steam_locomotive:
