### ISSUE TITLE
Relay emoji as unicode ✨

### ISSUE THREAD

**Issue by cben** [gitterHQ/irc-bridge#101]
I'm seeing emojis typed via colon syntax in gitter relayed by the bridge as-is, e.g. `:sparkles:`.
Could they be converted to unicode e.g. ✨?

For instance here are both colon syntax and unicode emojis in Chromium on Fedora 27, both rendered, though somewhat differently:
![captura de pantalla de 2018-02-15 17-46-43](https://user-images.githubusercontent.com/273688/36265690-7183eea2-1278-11e8-9a45-74513b077d41.png)

And here is same line via the IRC bridge, in irrsi in gnome-terminal, which recently started displaying unicode emojis in color, but naturally it doesn't do anything special with `:sparkles:`:
![captura de pantalla de 2018-02-15 17-43-29](https://user-images.githubusercontent.com/273688/36265379-c97f7f5a-1277-11e8-8542-647c15756602.png)

**Comment by MadLittleMods** [comment]
@cben I am going to close in favor of https://gitlab.com/gitlab-org/gitter/webapp/issues/1716 where this will probably just magically work.
