### ISSUE TITLE
Out of order messages

### ISSUE THREAD

**Issue by OlegYch** [gitterHQ/irc-bridge#102]
sometimes messages show up via irc long after they were sent, eg see screenshot
![ohz1ldigqvoytmkeuclf0a 1](https://user-images.githubusercontent.com/268312/36389283-a1be6df6-15af-11e8-86e7-ffc40dbe847c.png)

**Comment by MadLittleMods** [comment]
@OlegYch Can you permalink that point in the room (click on the timestamp in the top-right of the message)? It might help to know where in the webapp those other messages were in the order. 

Was that message resent (failed and turned red, then "Retry")? Wondering if it is related to [messages failing to send](https://gitlab.com/gitlab-org/gitter/webapp/issues/1863).

**Comment by OlegYch** [comment]
here is when the messages started appearing via irc https://gitter.im/scala/scala?at=5a8a08430202dc012e5208ab
not sure when or how they were sent originally...

**Comment by MadLittleMods** [comment]
@OlegYch I'm a bit confused by these duplicated messages, any insight? It appears like these rogue messages are the ones that randomly appeared in the IRC order.

Here is a summary of messages from your IRC client screenshot. ➡️ indicates the actual messages in the webapp.

 - ➡️ **"pshirshov did you get help with your issue?"**
    - (works fine, sent 2018-02-18T22:35:32.237Z) https://gitter.im/scala/scala?at=5a89ffb4888332ee3a9ea4bf
 - "apparently Dotty's grammar is context-free"
    - (works fine, sent 2018-02-16T23:08:27.663Z) https://gitter.im/scala/scala?at=5a87646b6fba1a703a5ea8bb
    - (permalink does not bring you to message, sent 2018-02-16T23:08:15.146Z) https://gitter.im/scala/scala?at=5a8a051cf4d013dc7c7d8028
 - "`Vector` is a good choice if you know you're not doing anything _super_ intensive, but you don't know which operations you might need."
    - (permalink does not bring you to message, sent 2018-02-16T23:14:50.590Z) https://gitter.im/scala/scala?at=5a8a0807f4d013dc7c7d8227
 - ➡️ **"which is pretty much always"**
    - (works fine, sent 2018-02-18T23:12:03.914Z), https://gitter.im/scala/scala?at=5a8a08430202dc012e5208ab
 - "Actually, I'm uncertain whether I'm wrong.  I can't remember the code.  One sec."
    - (permalink does not bring you to message, sent 2018-02-16T23:20:11.691Z), https://gitter.im/scala/scala?at=5a8a08adf4d013dc7c7d8258
 - "Yeah, I just wondered if anyone has seen this. Best is to open youtrack.jetbrains ticket. sbt in console works fine"
    - (works fine, sent 2018-02-16T23:26:33.483Z), https://gitter.im/scala/scala?at=5a8768a96fba1a703a5ec304
    - (permalink does not bring you to message, sent 2018-02-16T23:25:23.814Z), https://gitter.im/scala/scala?at=5a8a0954f4d013dc7c7d82c3

**Comment by OlegYch** [comment]
sorry, no idea
i could only guess that the duplication happened because someone clicked 'resend message'

**Comment by MadLittleMods** [comment]
@OlegYch "Retry" sent messages sounds plausible :+1:. In that case, the regular occurrence should be solved https://gitlab.com/gitlab-org/gitter/webapp/issues/1863

But I am still a bit confused why I can't find those messages in the room (via permalink or by scrolling). 

The only difference I can find is `"_md" : 11,` vs `_md" : -11,` which looks like is caused by following code but I don't see where we filter messages that have a negative `_md` 🤷‍♀️. `markdownProcessingFailed` probably was failing because of the same resolution in https://gitlab.com/gitlab-org/gitter/webapp/issues/1863

https://gitlab.com/gitlab-org/gitter/webapp/blob/599aa0d3fd638d43eef0f9c0d8758481f592e1f3/server/services/chat-service.js#L178
```
_md: parsedMessage.markdownProcessingFailed ? -CURRENT_META_DATA_VERSION : CURRENT_META_DATA_VERSION
```

---

:x: permalink does not bring you to message
```
db.chatmessages.findOne({ _id: ObjectId('5a8a051cf4d013dc7c7d8028') })
{
        "_id" : ObjectId("5a8a051cf4d013dc7c7d8028"),
        "fromUserId" : ObjectId("55118a7f15522ed4b3ddbe95"),
        "toTroupeId" : ObjectId("54db07fd15522ed4b3dbe0ae"),
        "text" : "apparently Dotty's grammar is context-free",
        "pub" : true,
        "html" : "apparently Dotty&#39;s grammar is context-free",
        "_md" : -11,
        "_tv" : 1,
        "readBy" : [
                ObjectId("556cd1bd15522ed4b3e142f8"),
                ObjectId("57e6722040f3a6eec06714f4"),
                ObjectId("54f6370715522ed4b3dcc261"),
                ObjectId("54f5db9e15522ed4b3dcbd78"),
                ObjectId("5690c98716b6c7089cc1cb93"),
                ObjectId("55e3e4fc0fc9f982beaf206f"),
                ObjectId("575d77d4c2f0db084a1d769f"),
                ObjectId("5540f13915522ed4b3dfb061"),
                ObjectId("5733cd8cc43b8c6019726735"),
                ObjectId("594287f4d73408ce4f67895f"),
                ObjectId("55e6b2550fc9f982beaf627a"),
                ObjectId("54b16334db8155e6700e86b3"),
                ObjectId("54f4b69115522ed4b3dcb16d"),
                ObjectId("56b3c0a1e610378809bfecc7"),
                ObjectId("5a6296d1d73408ce4f8932ec"),
                ObjectId("551a28c515522ed4b3de1342"),
                ObjectId("54ca70cedb8155e6700f3aa9"),
                ObjectId("5a1654d0d73408ce4f7fe689"),
                ObjectId("58dd1ba3d73408ce4f54e034"),
                ObjectId("54e0611415522ed4b3dc07c4"),
                ObjectId("56b9e907e610378809c093b2"),
                ObjectId("58c17e98d73408ce4f4f7d0a")
        ],
        "editedAt" : null,
        "sent" : ISODate("2018-02-16T23:08:15.146Z"),
        "issues" : [ ],
        "mentions" : [ ],
        "urls" : [ ],
        "__v" : 0
}
```

✔️ works fine
```
db.chatmessages.findOne({ _id: ObjectId('5a87646b6fba1a703a5ea8bb') })
{
        "_id" : ObjectId("5a87646b6fba1a703a5ea8bb"),
        "fromUserId" : ObjectId("55118a7f15522ed4b3ddbe95"),
        "toTroupeId" : ObjectId("54db07fd15522ed4b3dbe0ae"),
        "text" : "apparently Dotty's grammar is context-free",
        "pub" : true,
        "html" : "apparently Dotty&#39;s grammar is context-free",
        "lang" : "en",
        "_md" : 11,
        "_tv" : 1,
        "readBy" : [
                ObjectId("57ebe66440f3a6eec067d86e"),
                ObjectId("57ea759540f3a6eec0679ca1"),
                ObjectId("54f6370715522ed4b3dcc261"),
                ObjectId("550acee215522ed4b3dd8018"),
                ObjectId("556cd1bd15522ed4b3e142f8"),
                ObjectId("5690c98716b6c7089cc1cb93"),
                ObjectId("5540f13915522ed4b3dfb061"),
                ObjectId("575d77d4c2f0db084a1d769f"),
                ObjectId("54f5db9e15522ed4b3dcbd78"),
                ObjectId("5733cd8cc43b8c6019726735"),
                ObjectId("54b655eddb8155e6700ea47b"),
                ObjectId("58c17e98d73408ce4f4f7d0a"),
                ObjectId("55e6b2550fc9f982beaf627a"),
                ObjectId("556baa4015522ed4b3e1371a"),
                ObjectId("5a35f5a4d73408ce4f83ab4f"),
                ObjectId("54b16334db8155e6700e86b3"),
                ObjectId("54ca70cedb8155e6700f3aa9"),
                ObjectId("54e0611415522ed4b3dc07c4"),
                ObjectId("5797223c40f3a6eec05c7ee7"),
                ObjectId("58dd1ba3d73408ce4f54e034"),
                ObjectId("54f4b69115522ed4b3dcb16d"),
                ObjectId("56a0f6f8e610378809bd79f5"),
                ObjectId("58db9dd6d73408ce4f548ceb"),
                ObjectId("594287f4d73408ce4f67895f"),
                ObjectId("5a6296d1d73408ce4f8932ec"),
                ObjectId("59aadca1d73408ce4f740a9b")
        ],
        "editedAt" : null,
        "sent" : ISODate("2018-02-16T23:08:27.663Z"),
        "issues" : [ ],
        "mentions" : [ ],
        "urls" : [ ],
        "__v" : 0
}
```

**Comment by MadLittleMods** [comment]
I'll close for now as I think this has been resolved when we fixed https://gitlab.com/gitlab-org/gitter/webapp/issues/1863 but feel free to post back if you see this again.
