### ISSUE TITLE
Some messages are not sent

### ISSUE THREAD

**Issue by rom1504** [gitterHQ/irc-bridge#13]
I'm using the gitter--irc bridge and it usually works.
But sometimes it won't send the messages (from example between yesterday 00:38 and now on #PrismarineJS/node-minecraft-protocol).

**Comment by rom1504** [comment]
Some more information :
* it happened when I sent several messages and no one else did
* reconnecting to the server seemed to fix the problem (I can send messages again) : but that's not a real solution

**Comment by malditogeek** [comment]
According to the logs, looks like this was caused by a DNS disruption in two of the three IRC bridge instances. Will leave this open and will investigate further on Monday.

**Comment by rom1504** [comment]
It just happened again (a few minutes ago at 12:19)

**Comment by malditogeek** [comment]
@rom1504 I finally found the source of the problem. The `node-gitter` client inside the bridge was leaking file descriptors so after N days running, the process would reach it's limit and stop accepting connections and not being able to open new ones (to request for DNS names or anything else). The fix: https://github.com/gitterHQ/irc-bridge/commit/97255eeded5ee906ea551171114ab0eb37cd773b

This is in production already. Sorry about the hassle! :shipit:

**Comment by rom1504** [comment]
Thanks for the fix !
