### ISSUE TITLE
Unread messages when using the IRC bridge

### ISSUE THREAD

**Issue by bchretien** [gitterHQ/irc-bridge#20]
I keep getting notified by e-mail about unread messages even though I am currently reading these messages and answering to them on IRC. I can unsubscribe from the e-mail notifications, but then I may miss some messages sent while I was not on IRC. I don't know if there's a way around this though.

**Comment by mydigitalself** [comment]
If you are connected via the IRC bridge, the messages should immediately get marked as read. However, I've just tested a few permutations of this and noticed that this isn't true of 1:1 messages, is this the behaviour you are seeing?

**Comment by bchretien** [comment]
Yes, I've noticed that with 1:1 conversations indeed (and only in that case now that I think about it).

**Comment by mydigitalself** [comment]
@malditogeek this must be the issue I showed you today with 1:1's not being marked as read on IRC.

**Comment by malditogeek** [comment]
Yes, indeed. 1:1 messages are not being marked as read by the irc-bridge. Already devised a solution but will require changes in the API so the fix will take a bit longer, but it's on its way :+1:

**Comment by malditogeek** [comment]
shipped! :ship:
