### ISSUE TITLE
gitter-adapter: IRC Actions (/me) display as 'ACTION msg'

### ISSUE THREAD

**Issue by jimschubert** [gitterHQ/irc-bridge#3]
OS X LimeChat IRC Client:
![_jimschubert___gitterhq_gitter__1685__ask_questions___request_f](https://cloud.githubusercontent.com/assets/109659/6514700/697ccb5c-c352-11e4-8057-caca2912f0aa.png)

OS X Gitter Client (same in web):
![_gitterhq_gitter_-_gitter](https://cloud.githubusercontent.com/assets/109659/6514718/89aec632-c352-11e4-9cbc-33a88ea51ef9.png)

**Comment by malditogeek** [comment]
Oops, yes, I remember having to write a workaround for this on the old bridge, turns out `/me` is not a command but a "status" message with a prefix `\u0001ACTION` and a suffix `\u0001`

Will push a fix soon!
