### ISSUE TITLE
Comparison To Counterpart

### ISSUE THREAD

**Issue by Zensin** [gitterHQ/irc-bridge#32]
I've noticed that there are 2 bridges here on github, the other being https://github.com/finnp/gitter-irc-bot . What are the differences? Is one more feature rich or bug free than the other? I'm sure you've probably tested it. I realize this isn't an issue with yours but it's a good thread to have here.

Thanks.

**Comment by malditogeek** [comment]
@Zensin `finnp/gitter-irc-bot` is not a bridge, it's a client (a bot actually) that connects to the bridge. The code in this repo powers `irc.gitter.im` which is the official IRC bridge for Gitter. Hope that clarifies it.
