### ISSUE TITLE
Convert IRC style nick mentions to @-style

### ISSUE THREAD

**Issue by mkaito** [gitterHQ/irc-bridge#35]
Tab completion found in most IRC clients usually take the form of `nick: <message>`. This does not highlight the user in gitter, though. Prefixing with an `@` usually negates tab completion, making the workflow quite tiresome (tab complete a nick, delete colon, jump to start, add `@`).

**Comment by MadLittleMods** [comment]
Duplicate of https://github.com/gitterHQ/irc-bridge/issues/2 which points to https://github.com/gitterHQ/gitter/issues/158
