### ISSUE TITLE
Doesn't work with circ

### ISSUE THREAD

**Issue by cauburtin** [gitterHQ/irc-bridge#36]
![image](https://cloud.githubusercontent.com/assets/3134574/10963312/c239df7e-839f-11e5-83da-2c078d1d203b.png)

I tried putting the /pass and /nick and /pass again, there seems to be a problem

circ supports ssl

**Comment by malditogeek** [comment]
I managed to connect using the following command: `/server irc.gitter.im +6697 <TOKEN>`

![screen shot 2015-11-06 at 13 35 16](https://cloud.githubusercontent.com/assets/14751/10998256/c2360448-848b-11e5-9f2a-d29b2f5ded1e.png)

Also added some basic instructions in the wiki, feel free to edit them if you think it needs mode details: https://github.com/gitterHQ/irc-bridge/wiki/circ

**Comment by cauburtin** [comment]
thanks
