### ISSUE TITLE
Long messages are cut off in irc

### ISSUE THREAD

**Issue by raine** [gitterHQ/irc-bridge#39]
<img width="651" alt="screen shot 2015-11-21 at 10 30 37" src="https://cloud.githubusercontent.com/assets/11027/11317549/3123beda-903b-11e5-89b1-a9699f82bba0.png">

<img width="800" alt="screen shot 2015-11-21 at 10 30 14" src="https://cloud.githubusercontent.com/assets/11027/11317548/2df14674-903b-11e5-9199-8fd0f7ab18cd.png">

**Comment by MadLittleMods** [comment]
Hey Raine, This seems to be another client specific thing.

When using IRCCloud, a very long message is split across several messages.

**Comment by lucaswerkmeister** [comment]
This also usually works for me in Pidgin. Which client are you using @raine?

**Comment by raine** [comment]
How about when using gitter? Will people who use irc clients get long messages in multiple parts?

Sent from my iPhone

--
Raine

**Comment by lucaswerkmeister** [comment]
Yes, usually long messages are broken up into multiple IRC messages.

**Comment by MadLittleMods** [comment]
@raine Are you still running into this?

There was a couple fixes to splitting mesages a while ago. I suspect you were running into the colon `:` issue looking at your screenshots which was fixed in that PR https://github.com/gitterHQ/irc-bridge/pull/67
