### ISSUE TITLE
Message lag

### ISSUE THREAD

**Issue by mydigitalself** [gitterHQ/irc-bridge#4]
Messages seem to lag by ~15 seconds.

**Comment by suprememoocow** [comment]
This is probably fixed by https://github.com/gitterHQ/faye/commit/7a6514572294e136135484a70b76db6f5c448216

**Comment by malditogeek** [comment]
Just deployed this change. Keeping an eye on it :+1:

**Comment by OlegYch** [comment]
works much better so far

**Comment by malditogeek** [comment]
Fixed.
