### ISSUE TITLE
Invalid RPL_WHOREPLY for Gitter Bot

### ISSUE THREAD

**Issue by gdude2002** [gitterHQ/irc-bridge#53]
Here's a quick example.

Let's say we run `/who #GlowstonePlusPlus/GlowstonePlusPlus`, We'll get our stack of `RPL_WHOREPLY` messages, as expected.

`:irc.gitter.im 352 <my username> #GlowstonePlusPlus/GlowstonePlusPlus <their username> irc.gitter.im irc.gitter.im Egoscio H :0 <their realname>`

However, when we get to `gitter`, we get the following response:

`:irc.gitter.im 352 gdude2002 #GlowstonePlusPlus/GlowstonePlusPlus gitter :irc.gitter.im irc.gitter.im gitter H :0 Gitter Bot`

Note the extra `:` after `gitter ` and before `irc.gitter.im`.

Is there a reason for this? It seems to be breaking the parsing for various IRC bot frameworks.

**Comment by MadLittleMods** [comment]
I don't think there is a reason. Feel free to submit a PR

**Comment by gdude2002** [comment]
Alright, done.
