### ISSUE TITLE
Thunderbird 45.0 (Linux Mint 17.3 x86) fails to connect

### ISSUE THREAD

**Issue by Roman3349** [gitterHQ/irc-bridge#58]
I cannot to connect to Gitter IRC bridge in Mozilla Thunderbird 45.0. My operating system is Linux Mint 17.2 x86_64. 

**Log from Thunderbird**
> (Thunderbird 45.0 (20160209003915), Gecko 45.0 (20160209003915) on Linux x86_64)
> (96 messages omitted)
> [13.2.2016 12:44:24] LOG   (@ prpl-irc: Socket.connect resource:///modules/socket.jsm:148)
> Connecting to: irc.gitter.im:6697
> [13.2.2016 12:44:24] DEBUG (@ prpl-irc: Socket.onTransportStatus resource:///modules/socket.jsm:553)
> onTransportStatus(STATUS_RESOLVING)
> [13.2.2016 12:44:24] DEBUG (@ prpl-irc: Socket.onTransportStatus resource:///modules/socket.jsm:553)
> onTransportStatus(STATUS_RESOLVED)
> [13.2.2016 12:44:24] DEBUG (@ prpl-irc: Socket.onTransportStatus resource:///modules/socket.jsm:553)
> onTransportStatus(STATUS_CONNECTING_TO)
> [13.2.2016 12:44:24] DEBUG (@ prpl-irc: Socket.onTransportStatus resource:///modules/socket.jsm:553)
> onTransportStatus(STATUS_CONNECTED_TO)
> [13.2.2016 12:44:24] LOG   (@ prpl-irc: Socket.sendString resource:///modules/socket.jsm:255)
> Sending:
> CAP LS
> 
> [13.2.2016 12:44:24] LOG   (@ prpl-irc: Socket.sendString resource:///modules/socket.jsm:255)
> Sending:
> NICK Roman3349
> 
> [13.2.2016 12:44:24] LOG   (@ prpl-irc: Socket.sendString resource:///modules/socket.jsm:255)
> Sending:
> USER Thunderbird 0 * Roman3349
> 
> [13.2.2016 12:44:24] DEBUG (@ prpl-irc: Socket.onTransportStatus resource:///modules/socket.jsm:553)
> onTransportStatus(STATUS_SENDING_TO)
> [13.2.2016 12:44:29] DEBUG (@ prpl-irc: Socket.onTransportStatus resource:///modules/socket.jsm:553)
> onTransportStatus(STATUS_RECEIVING_FROM)
> [13.2.2016 12:44:29] DEBUG (@ prpl-irc: Socket.onStartRequest resource:///modules/socket.jsm:484)
> onStartRequest
> [13.2.2016 12:44:29] DEBUG (@ prpl-irc: ircSocket.prototype.onDataReceived resource://gre/components/irc.js:676)
> {"rawMessage":":gitter!gitter@irc.gitter.im PRIVMSG  : You must authenticate, check: https://irc.gitter.im","command":"PRIVMSG","params":[" You must authenticate, check: https://irc.gitter.im"],"origin":"gitter","user":"gitter","host":"irc.gitter.im","tags":{},"source":"gitter@irc.gitter.im"}
> [13.2.2016 12:44:29] ERROR (@ prpl-irc: GenericConversationPrototype.notifyObservers resource:///modules/jsProtoHelper.jsm:483)
> [Exception... "Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [mozITXTToHTMLConv.scanTXT]"  nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame :: resource:///modules/ircUtils.jsm :: <TOP_LEVEL> :: line 22"  data: no]
> [13.2.2016 12:44:29] DEBUG (@ prpl-irc: Socket.onStopRequest resource:///modules/socket.jsm:493)
> onStopRequest (0)
> [13.2.2016 12:44:29] WARN. (@ prpl-irc: ircSocket.prototype.onConnectionClosed resource://gre/components/irc.js:714)
> Connection closed by server.
> [13.2.2016 12:44:29] LOG   (@ prpl-irc: Socket.disconnect resource:///modules/socket.jsm:185)
> Disconnec

**Comment by MadLittleMods** [comment]
@Roman3349 Have you see these intructions on the wiki? https://github.com/gitterHQ/irc-bridge/wiki/Thunderbird

**Comment by Roman3349** [comment]
I'm sorry, but I guess I overlooked it.
