### ISSUE TITLE
Not getting direct messages

### ISSUE THREAD

**Issue by chriskacerguis** [gitterHQ/irc-bridge#74]
When connecting via IRC, I am able to send direct messages to people without problems, however I am not getting their responses (I have checked several IRC clients: IRCcloud, Textual5).

[update]: Channels (public) work fine, but not receiving direct messages.

**Comment by MadLittleMods** [comment]
Just to note, you don't join one to ones like normal rooms. Instead `/msg foouser`

I can send and receive messages in a one to one room via IRC but it seems to only work for a one to one I have already done this with on IRC previously.

I suspect this is an issue with `node-gitter`'s `room.join` and will need to wait for https://github.com/gitterHQ/docs/pull/41

**Comment by MadLittleMods** [comment]
Hey @chriskacerguis,

I looked into this a bit more and I don't think `room.join` is the issue.

What is your default notification setting set to? I suspect you are falling in this trap https://github.com/gitterHQ/gitter/issues/1275

I checked the user I was reproducing this issue with and it was set to `Announcements` which won't send out any `user_notification` for a normal message. I am pretty sure @suprememoocow did some work around this by always sending a notification for a one to one but those changes seemed to have never worked (or never worked from my understanding of it), see https://github.com/troupe/gitter-webapp/pull/1753

**Comment by chriskacerguis** [comment]
@MadLittleMods Can you confirm that link to troupe/gitter-webapp it returns 404.  Also, I'm set to mute with Announcement on a few 1:1 conversations. I'll change it tomorrow and let you know. 

That said, what is the status of the different notifications settings for 1:1 vs rooms, which was asked https://github.com/gitterHQ/gitter/issues/1275

**Comment by MadLittleMods** [comment]
@chriskacerguis It's a link to an internal project, you won't be able to see it.

Status would be on [that issue](https://github.com/gitterHQ/gitter/issues/1275). Actually separate settings for one-to-ones probably won't be addressed in the near future.

**Comment by chriskacerguis** [comment]
@MadLittleMods So, with the person that I was testing with on Gitter (and not getting their messages) I was set to "Announcement", as soon as I switched it to "All" it started to work.
