### ISSUE TITLE
irc.gitter.im is unreachable (although a blank page renders)

### ISSUE THREAD

**Issue by mhsjlw** [gitterHQ/irc-bridge#82]
I've tried 2 internet connections, 3 browsers and 2 devices and I can't access irc.gitter.im to retrieve my token. Apparently the bridge is up, but that's not much use to me :smile:

**Comment by nhooyr** [comment]
Seems to be up now.

**Comment by MadLittleMods** [comment]
See https://gitter.im/gitterHQ/irc-bridge?at=58984b68fef1d2de52a924f3
