### ISSUE TITLE
Extreme lag of 30 seconds

### ISSUE THREAD

**Issue by wadie** [gitterHQ/irc-bridge#92]
I keep having a lag of more than 30 seconds when receiving messages until at some point it disconnects from Gitter and reconnects..

Using Hexchat on Ubuntu 16.04

Is anyone else facing this issue ?

---

https://gitter.zendesk.com/agent/tickets/3873

**Comment by iPocket** [comment]
Its not really lagging, the PONG response argument is always specificated as "irc.gitter.im", not relaying the argument from PING from client.
HexChat sends for example: "PING LAG40483728" the numbers are microtime. then the server should response with "PONG LAG40483728", but it responds with "PONG irc.gitter.im" which is invalid.
I tried to fix that, but I still didn't understand JS code's OOP.

**Comment by iPocket** [comment]
See #34

**Comment by wadie** [comment]
Not really lagging, then why does it reconnect automatically every minute or so ?

**Comment by auscompgeek** [comment]
@wadie See #34 for the explanation.
