### ISSUE TITLE
Occasional parts on random channels

### ISSUE THREAD

**Issue by OlegYch** [gitterHQ/irc-bridge#94]
since a few days ago i'm experiencing unprovoked parts
eg i see " You have left channel #scala/scala" even though i was talking there a few minutes ago 
all i see in server log is  "PONG :irc.gitter.im"
i'm using hexchat on windows
this doesn't happen on freenode or other servers, but happens about once an hour on a random channel (one of 9 i'm on) on gitter

**Comment by MadLittleMods** [comment]
This might have to do with the recent changes in this PR https://github.com/gitterHQ/irc-bridge/pull/93

cc @Gargaj

**Comment by cpavlina** [comment]
I can confirm that I get this too. It seems most likely to happen if I also have the gitter web client open.

**Comment by rubdos** [comment]
Same here, on Weechat. Let me know if I can help sorting this out.

**Comment by OlegYch** [comment]
same with pircbotx
joining channel again doesn't seem to do anything

**Comment by amosbird** [comment]
Same, on weechat.

**Comment by LFlare** [comment]
Attempting to join channel again after `PART` has led to not being able to receive new messages as well.

**Comment by electronoob** [comment]
sigh.
unreliable gateway is unreliable.

**Comment by jwoglom** [comment]
I'm running into this issue on Weechat constantly. It happens every 2-3 days. Extremely frustrating.
