### ISSUE TITLE
Own messages show up as sent by "Gitter"

### ISSUE THREAD

**Issue by RalfJung** [gitterHQ/irc-bridge#97]
I am using Quassel to connect to Gitter's IRC bridge. When I send a message myself, it appears in my client as if sent by "Gitter".

I tried `/NICK RalfJung`, but that has no effect (other than a message saying "You are now known as RalfJung").

**Comment by MadLittleMods** [comment]
@RalfJung Does it work in another IRC client for you? If it does, perhaps we are missing some attribute that Quassel uses or just a bug in Quassel.

I just tested this on [IRCCloud](https://www.irccloud.com/) and it seems to work fine. 

![](https://i.imgur.com/DdUYKm9.png)

**Comment by RalfJung** [comment]
You are right, there does not seem to be a problem with Konversations either. Seems to be a Quassel issue. Not the first one... looks like I am looking for a new IRC client. :/

Anyway, thanks!
